# This workflow is triggered when a pull request is opened or updated.
# It will associate the pull request with the milestone that matches the version of the base branch + changelevel.
name: "Kanban"

on:
  pull_request:
    branches:
      - latest
    types:
      - opened
      - synchronize
      - reopened

jobs:
  on_pull_request:
    name: Pull Request
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: read
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-node@v3
    - run: npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
    - run: npm config set @pascalsalesch:registry https://npm.pkg.github.com
    - run: npm install -g @pascalsalesch/kanban
    - run: kanban run on_pull_request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_CONTEXT: ${{ toJson(github) }}
